behaviors:
  ContentGenerator:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 500000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 20.0
      learning_rate: 0.0003
      learning_rate_schedule: constant
      init_entcoef: 1.0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 6000000
    time_horizon: 128
    summary_freq: 20000